<!-- HEADER -->
<?php include APPROOT . '/views/inc/header.phtml'; ?>
<?php flash('update_message'); ?>

<main class="max-container">
    <h2> Mon Compte </h2>
   
    <section class="flex profile">
        <article>
            <h3>Mes Données</h3>

            <table>
                <tr>
                    <th>Prénom : </th>
                    <td> <?= htmlspecialchars($profil['firstname']) ?></td>
                </tr>
                <tr>
                    <th>Nom : </th>
                    <td> <?= htmlspecialchars($profil['lastname']) ?></td>
                </tr>
                <tr>
                    <th>Téléphone : </th>
                    <td> <?= htmlspecialchars($profil['phone']) ?></td>
                </tr>
                <tr>
                    <th>Email : </th>
                    <td> <?= htmlspecialchars($profil['email']) ?></td>
                </tr>
                <tr>
                    <th><a href="<?= URLROOT ?>/users/editprofil/<?= $profil['id'] ?>">Modifier mes données</a></th>
                </tr>
                <tr>
                    <th>
                        <a href="<?= URLROOT ?>/users/deleteprofil/<?= $profil['id'] ?>" id="delete-profil">Supprimer profil</a>
                    </th>
                </tr>
            </table>

        </article>

        <article>
            <h3>Adresse de Livraison</h3>
            <p>Votre adresse de livraison actuelle est : </p>
            <p class="Cap-fullname"><?= htmlspecialchars($profil['firstname']) . ' ' . htmlspecialchars($profil['lastname']) ?></p>
            <p><?= htmlspecialchars($profil['address']) ?></p>
            <p><?= htmlspecialchars($profil['zipcode']) . ' ' . htmlspecialchars($profil['city']) ?></p>
            <p><?= htmlspecialchars($profil['country']) ?></p>
        </article>

    </section>

    <section class="customers">
        <h3>Historique Commandes</h3>
        <?php foreach ($orderdetails as $orderdetail) : ?>
            <article>
                <h4><i class="fas fa-money-check"></i> Commande n°<?= $orderdetail['id'] ?> </h4>
                <div class="flex">
                    <h4><i class="fas fa-clock"></i> Date : <?= formatDate($orderdetail['creationtimestamp']) ?></h4>
                    <h4> Prix Total : <?= number_format($orderdetail['allTaxesIncluded'], 2) ?> <i class="fas fa-euro-sign"></i></h4>
                </div>
                <a href="<?= URLROOT ?>/users/customers/<?= $orderdetail['id'] ?>" id="show-details"> Voir Détails</a>

            </article>
        <?php endforeach; ?>
    </section>
</main>

<!-- FOOTER -->
<?php include APPROOT . '/views/inc/footer.phtml'; ?>