<!-- HEADER -->
<?php include APPROOT . '/views/inc/header.phtml'; ?>

<main class="main-initial">

    <!-- MESSAGE FLASH -->
    <?php flash('register_success'); ?>
    <?php flash('login_success'); ?>
    <?php flash('loginout_message') ?>
    <?php flash('mail_success') ?>
    <?php flash('validation_success') ?>
    <?php flash('delete_account') ?>

    <!-- GARAGE COAUTO -->
    <div class="bg-main">
        <section>
            
            <h1>Garage CO'AUTO</h1>
            
            <strong>
                Roulez en toute sérénité 
            </strong>

            <p>
                CO'AUTO vous accueille pour l'entretien et la réparation de votre véhicule, quelle que soit la marque de votre véhicule. Nous vous proposons des prestations techniques pour votre véhicule : échappement, embrayage, climatisation, vidange ...
            </p>
            <p> 
                Découvrez aussi toutes les promos auto. N'hésitez plus, rendez-vous chez CO'AUTO pour le diagnostic de votre véhicule.
            </p>

            <a href="#moreinfo" class="icon-square icon-square-green">Plus d'informations</a>
            
        </section>
    </div>

    <!--                   BANNER                              -->
    <section class="banner">
        <h2>La boutique en ligne</h2>
        <p>
            Retrouvez tous nos bons plans et profitez des meilleurs prix sur notre boutique en ligne
        </p>
        <a href="<?= URLROOT ?>/shopping/shop" class="icon-square icon-square-black"> Boutique</a>
    </section>

    <!--                   INFOS                              -->
    <div class="max-container">
        <section class="infos" id="moreinfo">
            <h2>Nous Connaitre</h2>

            <!-- LE GARAGE -->
            <article class="flex card">
                <div>
                    <h3 class="title-h3"> Le Garage </h3>
                    <p>
                        Nos garagistes mettront rapidement en œuvre les moyens nécessaires afin de répondre à votre demande. Contactez votre garagiste pour de plus amples informations ou pour toute question. </p>

                    <a href="#" class="icon-square icon-square-green "> Plus d'informations</a>
                </div>

                <figure>
                    <img src="img/nouscontacter/repair-tools1cc.jpg" alt="photo des informations">
                </figure>
            </article>

            <!-- NOS PRESTATIONS -->
            <article class="flex card">
                <figure>
                    <img src="img/nouscontacter/diagnos1.png" alt="photo des informations">
                </figure>
                <div>
                    <h3 class="title-h3"> Nos Prestations </h3>
                    <p>
                        Notre garage compte des professionnels qualifiés prêts à réaliser l’entretien, la réparation, le diagnostic de votre véhicule au meilleur prix.
                    </p>
                    <a href="<?= URLROOT ?>/pages/services" class="icon-square icon-square-green"> Nos Services</a>

                </div>
            </article>

            <!-- NOUS CONTACTER -->
            <article class="flex card">
                <div>
                    <h3 class="title-h3"> Nous contacter </h3>
                    <p>
                        Une question ou vous voulez prendre un rendez-vous ?

                        Contactez-nous par téléphone ou par message dans la rubrique contact
                    </p>
                    <a href="<?= URLROOT ?>/pages/contact" class="icon-square icon-square-green"> Nous Contacter</a>
                </div>
                
                <figure>
                    <img src="img/nouscontacter/diagnostic-resizeimagec.png" alt="photo des informations">
                </figure>
            </article>
        </section>

        <!-- NOUVEAUTES ARTICLES SLIDER -->
        <section>
            <h2>Nos Dernières Nouveautés</h2>
            <article id="slide">
                <div id="show-slide">
                    <?php foreach ($lastproducts as $lastProduct) : ?>
                        <figure class="pushup"><img src="<?= URLROOT ?>/img/shopping/<?= htmlspecialchars($lastProduct['picture']) ?>" alt="<?= htmlspecialchars($lastProduct['name']) ?>">
                            <figcaption><?= htmlspecialchars($lastProduct['name']) ?></figcaption>
                        </figure>
                    <?php endforeach; ?>
                </div>
            </article>
        </section>
    </div>
    
    <!-- Popup Covid -->
<section id="myPopup" class="popup">
        <!-- Modal content -->
        <article class="popup-content flex">

            <div class="popup-header">
                <span class="close"><i class="fas fa-times-circle"></i></span>
                <h3>Une triste nouvelle ...</h3>
            </div>
            
            <figure>
                <img src="<?= URLROOT ?>/public/img/bear-cry.gif" alt="Bear cry">
            </figure>
            
            <div class="popup-body">
                <p>En raison des conditions sanitaires actuelles, </p>
                <p> votre garage a fermé ses portes.</p>
                <p>Notre boutique en ligne est toujours disponible.</p>
            </div>
            
        </article>
    </section>

<script src="<?= URLROOT ?>/public/js/popupcovid.js"></script>

</main>

<!-- FOOTER -->
<?php include APPROOT . '/views/inc/footer.phtml'; ?>