<!-- FOOTER -->
<footer>
    <h3>Company Auto</h3>
    
    <nav class="social">
        <a href="<?= URLROOT ?>/pages/contact"><i class="fa fa-facebook-square"></i></a>
        <a href="<?= URLROOT ?>/pages/contact"><i class="fa fa-twitter-square"></i></a>
        <a href="<?= URLROOT ?>/pages/contact"><i class="fa fa-instagram"></i></a>
        <a href="<?= URLROOT ?>/pages/contact"><i class="fa fa-google"></i></a>
    </nav>

    <figure>
        <a href="<?= URLROOT ?>"><img src="<?= URLROOT ?>/public/img/logo-coauto-black.svg" alt="Logo coauto"></a>
    </figure>

    <small>Copyright © 2020 | Designed by Steve BRACO </small>

</footer>
</body>

<!-- JAVASCRIPT -->
<script src="<?= URLROOT ?>/public/js/main.js"></script>

</html>